### ISSUE TITLE
patched gameoflife.rock

### ISSUE THREAD

**Issue by gaborsch** [sylvainpolletvillard/gameofrockstars#1]
Here's a patched version of your code, fully Rockstar compliant and runs on Rocky interpreter (quite fast, to be honest). I don't want to patch it myself, check it and adjust if needed. 

I fixed the "Victory !" statement (missed `say`), and replaced the Quick Fire (fast Modulus) with my implementation.

It is a very nice job, well done!

https://github.com/gaborsch/rocky/blob/master/programs/gameoflife.rock

**Comment by sylvainpolletvillard** [comment]
Nice, thanks ! Sure you don't want to make a pull request, to get credit ?

I have deliberately omitted "say" before "Victory!", I don't want it to be actually printed in console, I just added this line so that the lyrics make sense :)

**Comment by sylvainpolletvillard** [comment]
I creditted you in the commit message, also removed some comments because true rockstars don't comment their own songs 😄

**Comment by gaborsch** [comment]
\m/
